version: '3.8'
# this is a flaprt docker-compose.yml file for the project
services:
  # Single API service with dynamic environment
  app:
    build:
      context: .
      args:
        APP_ENV: ${APP_ENV}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    env_file:
      - .env.${APP_ENV}
    environment:
      # Pass sensitive variables at runtime
      - APP_ENV=${APP_ENV}
      # - LLM_API_KEY=${LLM_API_KEY}
      # - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      # - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      # - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10m
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: on-failure
    networks:
      - common

networks:
  common:
    external: true

volumes:
  grafana-storage: 