global:
  scrape_interval: 10m
  evaluation_interval: 10m

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['app:8000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
